# HLint configuration file
# https://github.com/ndmitchell/hlint

- ignore: {name: Use liftA2} # Allow manual applicative style if clearer
- ignore: {name: Use <$>}
- ignore: {name: Use section}
- ignore: {name: Redundant bracket}

- arguments: [-XTypeApplications, -XOverloadedStrings, -XLambdaCase]

# Safety: Warn about partial functions
- warn: {lhs: head, rhs: safeHead}
- warn:
    lhs: fromJust x
    rhs: case x of Just y -> y; Nothing -> error ""
    note: "handled Maybe"
- warn:
    lhs: tail x
    rhs: case x of (y:ys) -> ys; [] -> error ""
    note: "handled list pattern matching"
