{-# LANGUAGE DeriveFunctor #-}
{-# LANGUAGE InstanceSigs #-}
{-# LANGUAGE TypeFamilies #-}

module Lambda.Stream
  ( -- * The Coinductive Stream Type
    Stream (..),
    headS,
    tailS,
    takeS,
    dropS,
    toListS,
    fromListInfinite,

    -- * Coinductive Constructors (Unfolds / Anamorphisms)
    unfoldS,
    iterateS,
    repeatS,
    cycleS,
    interleaveS,
    scanlS,
    zipWithS,

    -- * Representable & Indexing Operations
    indexS,
    tabulateS,
    diagonalS,

    -- * Isomorphism with Cofree Identity
    toCofree,
    fromCofree,

    -- * Classic Example Streams
    natsS,
    fibsS,
    alternatingBoolsS,
  )
where

import Control.Comonad (Comonad (..))
import Data.Distributive (Distributive (..))
import Data.Functor.Extend (Extend (..))
import Data.Functor.Rep (Representable (..))
import Data.Key (Key, Keyed (..), Lookup (..))
import Lambda.Free (Cofree ((:<)))
import Lambda.Functor (MyIdentity (..))
import Prelude hiding (lookup)

--------------------------------------------------------------------------------
-- 1. The Coinductive Stream Data Type
--------------------------------------------------------------------------------

-- | A coinductive infinite stream of elements of type @a@.
--
-- Unlike standard lists @[a] = Nil | Cons a [a]@, 'Stream' has no empty case
-- ('Nil'). Every 'Stream' is structurally guaranteed to be infinite.
--
-- Mathematically:
-- * In the category of sets/types, 'Stream' is the final coalgebra of the
--   base functor @StreamF a r = (a, r)@.
-- * Its cardinality for a base type @a@ is @|a|^ℵ₀@ (uncountably infinite
--   when @|a| >= 2@, such as @Stream Bool@).
-- * Isomorphic to @Nat -> a@ (hence a 'Representable' functor with 'Rep' = 'Int')
--   and isomorphic to @Cofree Identity a@.
data Stream a = Cons a (Stream a)
  deriving (Functor)

infixr 5 `Cons`

instance (Show a) => Show (Stream a) where
  show s = "Stream " ++ show (takeS 10 s) ++ "..."

-- | Extracts the first element of the stream (the counit/extract of the Comonad).
headS :: Stream a -> a
headS (Cons x _) = x

-- | Drops the first element and returns the remaining infinite stream.
tailS :: Stream a -> Stream a
tailS (Cons _ xs) = xs

-- | Takes the first @n@ elements of a 'Stream' as a finite list.
takeS :: Int -> Stream a -> [a]
takeS n _ | n <= 0 = []
takeS n (Cons x xs) = x : takeS (n - 1) xs

-- | Drops the first @n@ elements of a 'Stream' and returns the remaining stream.
dropS :: Int -> Stream a -> Stream a
dropS n s | n <= 0 = s
dropS n (Cons _ xs) = dropS (n - 1) xs

-- | Converts a 'Stream' into an infinite lazy Haskell list @[a]@.
toListS :: Stream a -> [a]
toListS (Cons x xs) = x : toListS xs

-- | Converts an infinite Haskell list into a 'Stream'.
-- Throws a runtime error if the input list terminates.
fromListInfinite :: [a] -> Stream a
fromListInfinite (x : xs) = Cons x (fromListInfinite xs)
fromListInfinite [] = error "fromListInfinite: expected an infinite list, got empty list"

--------------------------------------------------------------------------------
-- 2. Coinductive Constructors (Unfolds / Anamorphisms)
--------------------------------------------------------------------------------

-- | The fundamental anamorphism (unfold) for 'Stream'.
-- Given a coalgebra @s -> (a, s)@ and an initial seed @s@, produces the
-- unique infinite stream generated by iterating the coalgebra.
unfoldS :: (s -> (a, s)) -> s -> Stream a
unfoldS step seed =
  let (x, nextSeed) = step seed
   in Cons x (unfoldS step nextSeed)

-- | Repeatedly applies @f@ starting from @x@: @Cons x (Cons (f x) (Cons (f (f x)) ...))@
iterateS :: (a -> a) -> a -> Stream a
iterateS f = unfoldS (\a -> (a, f a))

-- | An infinite stream repeating the constant value @x@.
repeatS :: a -> Stream a
repeatS x = let s = Cons x s in s

-- | Cycles a non-empty finite list into an infinite 'Stream'.
cycleS :: [a] -> Stream a
cycleS [] = error "cycleS: cannot cycle an empty list"
cycleS xs = go xs
  where
    go [] = go xs
    go (y : ys) = Cons y (go ys)

-- | Interleaves two streams element by element: @a₀, b₀, a₁, b₁, a₂, b₂, ...@
interleaveS :: Stream a -> Stream a -> Stream a
interleaveS (Cons x xs) ys = Cons x (interleaveS ys xs)

-- | Lazy prefix scan over an infinite stream.
scanlS :: (b -> a -> b) -> b -> Stream a -> Stream b
scanlS f z (Cons x xs) = Cons z (scanlS f (f z x) xs)

-- | Zips two streams with a binary combiner function.
zipWithS :: (a -> b -> c) -> Stream a -> Stream b -> Stream c
zipWithS f (Cons x xs) (Cons y ys) = Cons (f x y) (zipWithS f xs ys)

--------------------------------------------------------------------------------
-- 3. Indexing, Tabulation, and Diagonalization
--------------------------------------------------------------------------------

-- | Extracts the @n@-th element (0-indexed) of a stream.
indexS :: Stream a -> Int -> a
indexS (Cons x _) 0 = x
indexS (Cons _ xs) n
  | n > 0 = indexS xs (n - 1)
  | otherwise = error "indexS: negative index"

-- | Constructs a stream by applying a generator function to every non-negative index @0, 1, 2, ...@
tabulateS :: (Int -> a) -> Stream a
tabulateS f = go 0
  where
    go i = Cons (f i) (go (i + 1))

-- | Extracts the main diagonal of a stream of streams:
-- @(s₀ !! 0), (s₁ !! 1), (s₂ !! 2), ...@
-- This is the categorical 'join' of the 'Stream' monad.
diagonalS :: Stream (Stream a) -> Stream a
diagonalS (Cons (Cons x _) xss) = Cons x (diagonalS (fmap tailS xss))

--------------------------------------------------------------------------------
-- 4. Categorical Typeclass Instances
--------------------------------------------------------------------------------

-- | Zipwise 'Applicative' instance.
instance Applicative Stream where
  pure :: a -> Stream a
  pure = repeatS

  (<*>) :: Stream (a -> b) -> Stream a -> Stream b
  Cons f fs <*> Cons x xs = Cons (f x) (fs <*> xs)

-- | Diagonal 'Monad' instance (isomorphic to the Reader monad @(->) Nat@).
instance Monad Stream where
  (>>=) :: Stream a -> (a -> Stream b) -> Stream b
  s >>= f = diagonalS (fmap f s)

-- | 'Distributive' instance: distributes any 'Functor' across an infinite 'Stream'.
instance Distributive Stream where
  distribute :: (Functor f) => f (Stream a) -> Stream (f a)
  distribute fs = Cons (fmap headS fs) (distribute (fmap tailS fs))

-- | 'Representable' instance witnessing @Stream a ≅ (Int -> a)@.
instance Representable Stream where
  type Rep Stream = Int
  tabulate :: (Int -> a) -> Stream a
  tabulate = tabulateS
  index :: Stream a -> Int -> a
  index = indexS

-- | Semi-comonadic 'Extend' instance.
instance Extend Stream where
  duplicated :: Stream a -> Stream (Stream a)
  duplicated s@(Cons _ xs) = Cons s (duplicated xs)

-- | Coinductive 'Comonad' instance where 'extract' is 'headS' and 'duplicate'
-- produces the stream of all suffixes ('tails').
instance Comonad Stream where
  extract :: Stream a -> a
  extract = headS

  duplicate :: Stream a -> Stream (Stream a)
  duplicate s@(Cons _ xs) = Cons s (duplicate xs)

  extend :: (Stream a -> b) -> Stream a -> Stream b
  extend f s@(Cons _ xs) = Cons (f s) (extend f xs)

type instance Key Stream = Int

instance Keyed Stream where
  mapWithKey :: (Int -> a -> b) -> Stream a -> Stream b
  mapWithKey f = go 0
    where
      go i (Cons x xs) = Cons (f i x) (go (i + 1) xs)

instance Lookup Stream where
  lookup :: Int -> Stream a -> Maybe a
  lookup i s
    | i < 0 = Nothing
    | otherwise = Just (indexS s i)

--------------------------------------------------------------------------------
-- 5. Isomorphism with Cofree MyIdentity
--------------------------------------------------------------------------------

-- | Converts a 'Stream' into its isomorphic 'Cofree' representation over 'MyIdentity'.
toCofree :: Stream a -> Cofree MyIdentity a
toCofree (Cons x xs) = x :< Id (toCofree xs)

-- | Converts a @Cofree MyIdentity a@ into a 'Stream'.
fromCofree :: Cofree MyIdentity a -> Stream a
fromCofree (x :< Id xs) = Cons x (fromCofree xs)

--------------------------------------------------------------------------------
-- 6. Classic Example Streams
--------------------------------------------------------------------------------

-- | The infinite stream of natural numbers: @0, 1, 2, 3, ...@
natsS :: Stream Int
natsS = iterateS (+ 1) 0

-- | The infinite stream of Fibonacci numbers: @0, 1, 1, 2, 3, 5, 8, 13, ...@
fibsS :: Stream Integer
fibsS = Cons 0 (Cons 1 (zipWithS (+) fibsS (tailS fibsS)))

-- | The alternating boolean stream: @True, False, True, False, ...@
alternatingBoolsS :: Stream Bool
alternatingBoolsS = cycleS [True, False]
